<?php

/**
 * @file
 */

/**
 * Implements hook_install().
 */
function tripal_eutils_install() {

  chado_insert_cv('ncbi_properties',
    'The ncbi BioSample properties CV is downloaded from https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/?format=xml.');

  chado_insert_cvterm([
    'id' => 'local:full_ncbi_xml',
    'name' => 'full_ncbi_xml',
    'cv_name' => 'local',
  ]);

  chado_insert_cvterm([
    'id' => 'local:ncbi_FTP_links',
    'name' => 'NCBI Data Download FTP Link',
    'cv_name' => 'local',
  ]);

  chado_insert_cvterm(
    [
      'id' => 'ncbi_properties:submitter_provided_accession',
      'name' => 'submitter_provided_accession',
      'cv_name' => 'ncbi_properties',
    ]
  );


  tripal_eutils_add_dbs();
  tripal_eutils_insert_biosample_attribute_terms();
  tripal_eutils_install_chado_1_4_tables();

}

/**
 * Extra biosample property terms discovered in @ticket 170.
 */
function tripal_eutils_insert_extra_biosample_terms() {

  tripal_insert_cvterm(
    [
      'id' => 'ncbi_properties:samples provided by',
      'name' => 'Samples provided by',
      'def' => '',
      'cv_name' => 'ncbi_properties',
    ]
  );

  tripal_insert_cvterm(
    [
      'id' => 'ncbi_properties:Publication',
      'name' => 'Publication',
      'def' => '',
      'cv_name' => 'ncbi_properties',
    ]
  );
  tripal_insert_cvterm(
    [
      'id' => 'ncbi_properties:note',
      'name' => 'Note',
      'def' => 'Misc. free text.',
      'cv_name' => 'ncbi_properties',
    ]
  );
}

/**
 *Adds attribute terms for properties.
 */
function tripal_eutils_insert_biosample_attribute_terms() {

  $file = __DIR__ . '/mappings/biosample/xml_releases/11-30-18.xml';

  $lookup = new \BiosamplePropertyLookup($file);

  $terms = $lookup->lookupAll();

  foreach ($terms as $machine_name => $attributes) {

    tripal_insert_cvterm(
      [
        'id' => 'ncbi_properties:' . $machine_name,
        'name' => $attributes['label'],
        'def' => $attributes['def'],
        'cv_name' => 'ncbi_properties',
      ]
    );
  }
  // Version 1.0 as of November 29 2018: 456 terms.
}

/**
 * Implements hook_schema()
 */
function tripal_eutils_schema() {

  // This table is not currently used.  It would allow admins to use custom cvterms when loading in properties.  However, for now we want to limit this.
  $schema['tripal_eutils_tag_dictionary'] = [
    'description' => 'Stores all attribute tags encountered and their mappings',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'tag' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'The XML tag name.',
      ],
      'type' => [
        'description' => 'NCBI database type.',
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
      ],
      'status' => [
        'description' => 'assigned, unassigned, ignored',
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
      ],

      'cvterm_id' => [
        'description' => 'The cvterm this tag is mapped to.',
        'type' => 'int',
        'not null' => FALSE,
      ],
    ],
    'primary key' => [
      'id',
    ],
  ];

  return $schema;
}

/**
 * Add chado db records.
 */
function tripal_eutils_add_dbs() {
  tripal_insert_db(
    [
      'name' => 'NCBI BioSample',
      'description' => 'The BioSample database contains descriptions of biological source materials used in experimental assays.',
      'urlprefix' => 'http://www.ncbi.nlm.nih.gov/biosample/{accession}',
      'url' => 'http://www.ncbi.nlm.nih.gov/biosample/',
    ]
  );
  chado_insert_db([
    'name' => 'NCBI SRA',
    'url' => 'https://www.ncbi.nlm.nih.gov/sra/',
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/sra/{accession}',
  ]);

  chado_insert_db([
    'name' => 'ncbi_properties',
    'description' => 'Attribute and property terms for NCBI.',
    'url' => 'http://www.ncbi.nlm.nih.gov/',
  ]);

  chado_insert_db([
    'name' => 'NCBI WGS',
    'url' => 'https://www.ncbi.nlm.nih.gov/Traces/wgs/',
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/Traces/wgs/{accession}',
  ]);

  chado_insert_db([
    'name' => 'NCBI Refseq',
    'description' => 'A comprehensive, integrated, non-redundant, well-annotated set of reference sequences including genomic, transcript, and protein.',
    'url' => 'https://www.ncbi.nlm.nih.gov/refseq/',
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/refseq/{accession}',

  ]);

  chado_insert_db([
    'name' => 'NCBI GenBank',
    'description' => 'GenBank ® is the NIH genetic sequence database, an annotated collection of all publicly available DNA sequences (Nucleic Acids Research, 2013 Jan;41(D1):D36-42).',
    'url' => 'https://www.ncbi.nlm.nih.gov/genbank/',
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/genbank/{accession}',
  ]);
  chado_insert_db([
    'name' => 'NCBI BioProject',
    'description' => "A BioProject is a collection of biological data related to a single initiative, originating from a single organization or from a consortium.",
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/bioproject/{accession}',
    'url' => 'https://www.ncbi.nlm.nih.gov/bioproject/',
  ]);

  chado_insert_db([
    'name' => 'NCBI Assembly',
    'description' => "A database providing information on the structure of assembled genomes, assembly names and other meta-data, statistical reports, and links to genomic sequence data..",
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/assembly/{accession}',
    'url' => 'https://www.ncbi.nlm.nih.gov/assembly/',
  ]);

  tripal_eutils_create_dbs_for_assembly_xrefs();
}

/**
 * Adds Chado linker tables this module needs.
 *
 * These tables will be in the Chado 1.4 release so let's add them here for now.
 */
function tripal_eutils_install_chado_1_4_tables() {

  $schema = [
    'fields' => [
      'biomaterial_project_id' => ['type' => 'serial', 'not null' => TRUE],
      'biomaterial_id' => ['type' => 'int', 'not null' => TRUE],
      'project_id' => ['type' => 'int', 'not null' => TRUE],
    ],
    'primary key' => ['biomaterial_project_id'],
    'foreign keys' => [
      'biomaterial' => [
        'table' => 'biomaterial',
        'columns' => [
          'biomaterial_id' => 'biomaterial_id',
        ],
      ],
      'project' => [
        'table' => 'project',
        'columns' => [
          'project_id' => 'project_id',
        ],
      ],
    ],
    'indexes' => [
      'biomaterial_project_idx1' => ['biomaterial_id'],
      'biomaterial_project_idx2' => ['project_id'],
    ],
    'unique keys' => [
      'biomaterial_project_unique_uq1' => ['biomaterial_id', 'project_id'],
    ],
  ];

  chado_create_custom_table('biomaterial_project', $schema, TRUE, NULL, FALSE);

}


/**
 * Creates db entries for keys introduced in hte assembly loader.
 *
 */
function tripal_eutils_create_dbs_for_assembly_xrefs() {

  chado_insert_db([
    'name' => 'Refseq Assembly',
    'description' => "A database providing information on the structure of assembled genomes, assembly names and other meta-data, statistical reports, and links to genomic sequence data..",
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/assembly/{accession}',
    'url' => 'https://www.ncbi.nlm.nih.gov/assembly/',
  ]);

  chado_insert_db([
    'name' => 'Genbank Assembly',
    'description' => "A database providing information on the structure of assembled genomes, assembly names and other meta-data, statistical reports, and links to genomic sequence data..",
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/assembly/{accession}',
    'url' => 'https://www.ncbi.nlm.nih.gov/assembly/',
  ]);

}
/**
 * Add extra property terms.
 */
function tripal_eutils_update_7301() {
  tripal_eutils_insert_extra_biosample_terms();

}

/**
 * Add extra databases
 */
function tripal_eutils_update_7302(){
  tripal_eutils_create_dbs_for_assembly_xrefs();

}
